//--------------------------------------------------
// Enumerations of User Timer Events
//--------------------------------------------------
    _USER_TIMER_EVENT_KEY_REPEAT_ENABLE,
    _USER_TIMER_EVENT_KEY_SCAN_READY,
    _USER_TIMER_EVENT_OSD_DISABLE_OSD_LOGO,
    _USER_TIMER_EVENT_OSD_SHOW_NO_CABLE,
    _USER_TIMER_EVENT_OSD_SHOW_NO_SIGNAL,
    _USER_TIMER_EVENT_OSD_SHOW_POWER_SAVING,
    _USER_TIMER_EVENT_GO_TO_POWER_SAVING,
    _USER_TIMER_EVENT_OSD_DISABLE,
    _USER_TIMER_EVENT_PANEL_BACKLIGHT_ON,
    _USER_TIMER_EVENT_PANEL_POWER_OFF,
    _USER_TIMER_EVENT_DO_AUTO_COLOR,
    _USER_TIMER_EVENT_PANEL_USED_TIMER,

#if(_HIGHLIGHT_WINDOW_SUPPORT == _ON)
    _USER_TIMER_EVENT_HLWIN_TYPE5_MOVE,
#endif

    _USER_TIMER_EVENT_OSD_KEYINFO_UNHIGHLIGHT,
    _USER_TIMER_EVENT_OSD_SHOW_DP_VERSION_SELECT,

	_USER_TIMER_EVENT_OSD_DISPLAYMODE_SELECT,

#if(_FREESYNC_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_SHOW_FREESYNC_VFREQ,
#endif

#if(_FREEZE_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_DISABLE_FREEZE_MSG,
#endif
#if	(_ENABLE_LIGHT_SENSOR == _ON)
	_USER_TIMER_EVENT_CHECK_BACKLIGHT,
#endif

#if (_ENABLE_FAN_CONTROL == _ON)
	_USER_TIMER_EVENT_CHECK_FANCONTROL,
#endif

#if	(_ENABLE_SELF_CHECK == _ON)
	_USER_TIMER_EVENT_CHECK_SELF,
#endif

#if (_ENABLE_MENU_OLED == _ON)
		_USER_TIMER_EVENT_OSD_JB_RUN,
		_USER_TIMER_EVENT_OSD_OFF_RS_RUN,
		_USER_TIMER_EVENT_LED_BLINKING_TIMER,
		_USER_TIMER_EVENT_JB_END_TIMER,
		_USER_TIMER_EVENT_OFFRS_END_TIMER,
		_USER_TIMER_EVENT_OSD_POWER_OFF,
#endif
#if(_CUSTOMER_TYPE == _CUSTOMER_HUBIT)
		_USER_TIMER_EVENT_BOOT_PWMSET,
#endif
//#if (_PANEL_IDX_NAME == _PANEL_DV550QUM_N10	)
//	_USER_TIMER_EVENT_PANEL_I2C,
//#endif

#if(_CUSTOMER_TYPE == _CUSTOMER_MRK)
_USER_TIMER_EVENT_BOOT_GPIO1_DELAY,
#endif

#if(_PIXEL_SHIFT_SUPPORT == _ON)
_USER_TIMER_EVENT_PIXEL_SHIFT,
#endif
