//--------------------------------------------------
// Enumerations of User Timer Events
//--------------------------------------------------
    _USER_TIMER_EVENT_KEY_REPEAT_ENABLE,
    _USER_TIMER_EVENT_KEY_SCAN_READY,
    _USER_TIMER_EVENT_OSD_DISABLE_OSD_LOGO,
    _USER_TIMER_EVENT_OSD_SHOW_NO_CABLE,
    _USER_TIMER_EVENT_OSD_SHOW_NO_SIGNAL,
    _USER_TIMER_EVENT_OSD_SHOW_POWER_SAVING,
    _USER_TIMER_EVENT_GO_TO_POWER_SAVING,
    _USER_TIMER_EVENT_OSD_DISABLE,
    _USER_TIMER_EVENT_PANEL_BACKLIGHT_ON,
    _USER_TIMER_EVENT_PANEL_POWER_OFF,
    _USER_TIMER_EVENT_DO_AUTO_COLOR,
    _USER_TIMER_EVENT_PANEL_USED_TIMER,

#if(_HIGHLIGHT_WINDOW_SUPPORT == _ON)
    _USER_TIMER_EVENT_HLWIN_TYPE5_MOVE,
#endif
    _USER_TIMER_EVENT_OSD_SHOW_DP_VERSION_SELECT,

#if(_HDMI_CEC_SUPPORT == _ON)
    _USER_TIMER_EVENT_CEC_LA_POLLING,
#endif

#if(_FREESYNC_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_SHOW_FREESYNC_VFREQ,
#endif

#if(_FREEZE_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_DISABLE_FREEZE_MSG,
#endif

#if(_LD_HDR10_BOOST_SUPPORT == _ON)
     _USER_TIMER_EVENT_HDR_BOOST,
     _USER_TIMER_EVENT_HDR_COOL,
#endif
	_USER_TIMER_EVENT_LCD_TEST,
#if (_ENABLE_MENU_OLED == _ON)
	_USER_TIMER_EVENT_OSD_JB_RUN,
	_USER_TIMER_EVENT_OSD_OFF_RS_RUN,
	_USER_TIMER_EVENT_LED_BLINKING_TIMER,
	_USER_TIMER_EVENT_JB_END_TIMER,
	_USER_TIMER_EVENT_OFFRS_END_TIMER,
	_USER_TIMER_EVENT_OSD_POWER_OFF,
	_USER_TIMER_EVENT_OSD_POWER_OFF_OFFRS_RUN,
	_USER_TIMER_EVENT_OSD_POWER_SAVING,
	_USER_TIMER_EVENT_OSD_POWER_SAVE_OFFRS_RUN,
#endif
	_USER_TIMER_EVENT_FUNCTION_TEST,		
	_USER_TIMER_EVENT_DPMS_LED_TOGGLE,		
	_USER_TIMER_EVENT_BURNIN_PROCESS,		
	_USER_TIMER_EVENT_TEMPSENSOR_READ,		
	_USER_TIMER_EVENT_LUXSENSOR_READ,	
    
    _USER_TIMER_EVENT_HOTKEY_SOURCE_CHANGE,	
	_USER_TIMER_OSDEVENT_SAVE_NVRAM_OSDUSERDATA_MSG,
