#define _PANEL_PWM_MAX                          0x800
#define _PANEL_PWM_MIN                          0x2A8
#define _PANEL_PWM_DELTA_MAX                    (_PANEL_PWM_MAX - _PANEL_PWM_MIN)
#define _PANEL_LV_MAX                           0x112
#define _PANEL_LV_MIN                           0x05C
#define _PANEL_LV_BOOST_MAX                     0x1A4
#define _PANEL_LV_BOOST_MIN                     0x08C
#define _REGION0_PWM_TO_LV_OWN                  0x07
#define _REGION0_PWM_TO_LV_REGION1              0x37
#define _REGION1_PWM_TO_LV_OWN                  0x07
#define _REGION1_PWM_TO_LV_REGION0              0x3D
#define _REGION1_PWM_TO_LV_REGION2              0x38
#define _REGION2_PWM_TO_LV_OWN                  0x07
#define _REGION2_PWM_TO_LV_REGION1              0x3A
#define _REGION2_PWM_TO_LV_REGION3              0x38
#define _REGION3_PWM_TO_LV_OWN                  0x07
#define _REGION3_PWM_TO_LV_REGION2              0x3B
#define _REGION3_PWM_TO_LV_REGION4              0x34
#define _REGION4_PWM_TO_LV_OWN                  0x07
#define _REGION4_PWM_TO_LV_REGION3              0x38
#define _REGION4_PWM_TO_LV_REGION5              0x39
#define _REGION5_PWM_TO_LV_OWN                  0x07
#define _REGION5_PWM_TO_LV_REGION4              0x3E
#define _REGION5_PWM_TO_LV_REGION6              0x38
#define _REGION6_PWM_TO_LV_OWN                  0x07
#define _REGION6_PWM_TO_LV_REGION5              0x3A
#define _REGION6_PWM_TO_LV_REGION7              0x37
#define _REGION7_PWM_TO_LV_OWN                  0x07
#define _REGION7_PWM_TO_LV_REGION6              0x38
