//--------------------------------------------------
// Enumerations of Scaler Timer Events
//--------------------------------------------------
#if((_DVI_SUPPORT == _ON) || (_HDMI_SUPPORT == _ON))

#if(_DVI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX0_TMDS_VIDEO_DETECT,
#if(_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX0_TMDS_HDMI_PACKET_DETECT,
#if(_D0_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX0_HDMI_HPD_ASSERTED,
#endif
#endif
#endif
#if(_D1_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX1_TMDS_VIDEO_DETECT,
#if(_D1_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX1_TMDS_HDMI_PACKET_DETECT,
    _SCALER_TIMER_EVENT_RX1_HDMI_HPD_ASSERTED,
#endif
#endif
#if(_D2_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX2_TMDS_VIDEO_DETECT,
#if(_D2_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX2_TMDS_HDMI_PACKET_DETECT,
    _SCALER_TIMER_EVENT_RX2_HDMI_HPD_ASSERTED,
#endif
#endif
#if(_D3_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_TMDS_VIDEO_DETECT,
#if(_D3_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_TMDS_HDMI_PACKET_DETECT,
    _SCALER_TIMER_EVENT_RX3_HDMI_HPD_ASSERTED,
#endif
#endif
#if(_D4_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_TMDS_VIDEO_DETECT,
#if(_D4_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_TMDS_HDMI_PACKET_DETECT,
#endif
#endif
#if(_D5_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX5_TMDS_VIDEO_DETECT,
#if(_D5_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX5_TMDS_HDMI_PACKET_DETECT,
#endif
#endif

    _SCALER_TIMER_EVENT_TMDS_EMP_DETECT,

#if(_TMDS_Z0_POWER_SAVING_TOGGLE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_TMDS_Z0_POWER_SAVING_TOGGLE_LOW_DUTY,
    _SCALER_TIMER_EVENT_TMDS_Z0_POWER_SAVING_TOGGLE_HIGH_DUTY,
#endif

#if(_HDMI_SUPPORT == _ON)
#if(_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX0_HDMI2_FORMAT_RESET_WAIT,
    _SCALER_TIMER_EVENT_RX0_HDMI2_SCRAMBLE_DETECT_TIMEOUT,
#if(_D1_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX1_HDMI2_FORMAT_RESET_WAIT,
    _SCALER_TIMER_EVENT_RX1_HDMI2_SCRAMBLE_DETECT_TIMEOUT,
#endif
#if(_D2_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX2_HDMI2_FORMAT_RESET_WAIT,
    _SCALER_TIMER_EVENT_RX2_HDMI2_SCRAMBLE_DETECT_TIMEOUT,
#endif
#if(_D3_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_HDMI2_FORMAT_RESET_WAIT,
    _SCALER_TIMER_EVENT_RX3_HDMI2_SCRAMBLE_DETECT_TIMEOUT,
#endif
#if(_D4_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_HDMI2_FORMAT_RESET_WAIT,
    _SCALER_TIMER_EVENT_RX4_HDMI2_SCRAMBLE_DETECT_TIMEOUT,
#endif
#if(_D5_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX5_HDMI2_FORMAT_RESET_WAIT,
    _SCALER_TIMER_EVENT_RX5_HDMI2_SCRAMBLE_DETECT_TIMEOUT,
#endif
#endif // #if(_HDMI_2_0_SUPPORT == _ON)
#endif // #if(_HDMI_SUPPORT == _ON)

#endif // #if((_DVI_SUPPORT == _ON) || (_HDMI_SUPPORT == _ON))

#if(_HDCP_2_2_SUPPORT == _ON)
#if((_D0_INPUT_PORT_TYPE == _D0_HDMI_PORT) || (_D0_INPUT_PORT_TYPE == _D0_MHL_PORT))
    _SCALER_TIMER_EVENT_RX0_HDCP2_REAUTH,
#endif
#if((_D1_INPUT_PORT_TYPE == _D1_HDMI_PORT) || (_D1_INPUT_PORT_TYPE == _D1_MHL_PORT))
    _SCALER_TIMER_EVENT_RX1_HDCP2_REAUTH,
#endif
#if((_D2_INPUT_PORT_TYPE == _D2_HDMI_PORT) || (_D2_INPUT_PORT_TYPE == _D2_MHL_PORT))
    _SCALER_TIMER_EVENT_RX2_HDCP2_REAUTH,
#endif
#if((_D3_INPUT_PORT_TYPE == _D3_HDMI_PORT) || (_D3_INPUT_PORT_TYPE == _D3_MHL_PORT))
    _SCALER_TIMER_EVENT_RX3_HDCP2_REAUTH,
#endif
#if((_D4_INPUT_PORT_TYPE == _D4_HDMI_PORT) || (_D4_INPUT_PORT_TYPE == _D4_MHL_PORT))
    _SCALER_TIMER_EVENT_RX4_HDCP2_REAUTH,
#endif
#if((_D5_INPUT_PORT_TYPE == _D5_HDMI_PORT) || (_D5_INPUT_PORT_TYPE == _D5_MHL_PORT))
    _SCALER_TIMER_EVENT_RX5_HDCP2_REAUTH,
#endif
#endif

#if(_AUDIO_SUPPORT == _ON)
#if((_HDMI_SUPPORT == _ON) || (_DP_SUPPORT == _ON))
    _SCALER_TIMER_EVENT_AUDIO_D0_LOAD_STABLE_I_CODE,
#if(_HDMI_AUDIO_FW_TRACKING_MODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D0_FW_TRACKING_PREPARING,
    _SCALER_TIMER_EVENT_AUDIO_D0_FW_TRACKING_TIMEOUT,
#endif
#endif
#if((_D1_HDMI_SUPPORT == _ON) || (_D1_INPUT_PORT_TYPE == _D1_DP_PORT))
    _SCALER_TIMER_EVENT_AUDIO_D1_LOAD_STABLE_I_CODE,
#if(_HDMI_AUDIO_FW_TRACKING_MODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D1_FW_TRACKING_PREPARING,
    _SCALER_TIMER_EVENT_AUDIO_D1_FW_TRACKING_TIMEOUT,
#endif
#endif
#if((_D2_HDMI_SUPPORT == _ON) || (_D2_INPUT_PORT_TYPE == _D2_DP_PORT))
    _SCALER_TIMER_EVENT_AUDIO_D2_LOAD_STABLE_I_CODE,
#if(_HDMI_AUDIO_FW_TRACKING_MODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D2_FW_TRACKING_PREPARING,
    _SCALER_TIMER_EVENT_AUDIO_D2_FW_TRACKING_TIMEOUT,
#endif
#endif
#if(_D3_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D3_LOAD_STABLE_I_CODE,
#if(_HDMI_AUDIO_FW_TRACKING_MODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D3_FW_TRACKING_PREPARING,
    _SCALER_TIMER_EVENT_AUDIO_D3_FW_TRACKING_TIMEOUT,
#endif
#endif
#if(_D4_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D4_LOAD_STABLE_I_CODE,
#if(_HDMI_AUDIO_FW_TRACKING_MODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D4_FW_TRACKING_PREPARING,
    _SCALER_TIMER_EVENT_AUDIO_D4_FW_TRACKING_TIMEOUT,
#endif
#endif
#if(_D5_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D5_LOAD_STABLE_I_CODE,
#if(_HDMI_AUDIO_FW_TRACKING_MODE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D5_FW_TRACKING_PREPARING,
    _SCALER_TIMER_EVENT_AUDIO_D5_FW_TRACKING_TIMEOUT,
#endif
#endif
#endif // End of #if(_AUDIO_SUPPORT == _ON)

#if(_DP_SUPPORT == _ON)
#if((_D0_INPUT_PORT_TYPE == _D0_DP_PORT) || (_D6_INPUT_PORT_TYPE != _D6_NO_PORT))
    _SCALER_TIMER_EVENT_DP_RX0_HOTPLUG_ASSERTED,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_LINK_STATUS_IRQ,
#endif // End of #if((_D0_INPUT_PORT_TYPE == _D0_DP_PORT) || (_D6_INPUT_PORT_TYPE != _D6_NO_PORT))
#if(_D1_INPUT_PORT_TYPE == _D1_DP_PORT)
    _SCALER_TIMER_EVENT_DP_RX1_HOTPLUG_ASSERTED,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_LINK_STATUS_IRQ,
#endif // End of #if(_D1_INPUT_PORT_TYPE == _D1_DP_PORT)
#if(_D2_INPUT_PORT_TYPE == _D2_DP_PORT)
    _SCALER_TIMER_EVENT_DP_RX2_HOTPLUG_ASSERTED,
    _SCALER_TIMER_EVENT_DP_RX2_HDCP_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX2_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX2_LINK_STATUS_IRQ,
#endif // End of #if(_D2_INPUT_PORT_TYPE == _D2_DP_PORT)

#if(_D0_DP_EXIST == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_VALID_SIGNAL_DETECT_CHECK,
#if(_ULTRA_HDR_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_RSV0_PACKET_DETECT,
#endif
#if((_DP_VSC_SDP_EXT_FOR_COLORIMETRY_SUPPORT == _ON) && (_HW_DP_VSC_SDP_REG_SUPPORT != _ON))
    _SCALER_TIMER_EVENT_DP_RX0_RSV1_PACKET_DETECT,
#endif
#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_AUX_CH_NO_POWER_CHECK_DEBOUNCE,
    _SCALER_TIMER_EVENT_DP_RX0_SOURCE_WRITE_POWER_UP_TIMEOUT,
#if(_DP_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_READ_IRQ_TIMEOUT,
#if((_DP_VSC_SDP_EXT_FOR_COLORIMETRY_SUPPORT == _ON) && (_HW_DP_VSC_SDP_REG_SUPPORT != _ON))
    _SCALER_TIMER_EVENT_DP_RX0_MST2SST_RSV1_PACKET_DETECT,
#endif
#if(_DP_HDCP_2_2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_HDCP2_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP2_REPEATER_PROC_TIMEOUT,
#endif
#endif // End of #if(_DP_TX_SUPPORT == _ON)
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#endif // End of #if(_D0_DP_EXIST == _ON)

#if(_D1_DP_EXIST == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_VALID_SIGNAL_DETECT_CHECK,
#if(_ULTRA_HDR_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_RSV0_PACKET_DETECT,
#endif
#if((_DP_VSC_SDP_EXT_FOR_COLORIMETRY_SUPPORT == _ON) && (_HW_DP_VSC_SDP_REG_SUPPORT != _ON))
    _SCALER_TIMER_EVENT_DP_RX1_RSV1_PACKET_DETECT,
#endif
#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_AUX_CH_NO_POWER_CHECK_DEBOUNCE,
    _SCALER_TIMER_EVENT_DP_RX1_SOURCE_WRITE_POWER_UP_TIMEOUT,
#if(_DP_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_READ_IRQ_TIMEOUT,
#if((_DP_VSC_SDP_EXT_FOR_COLORIMETRY_SUPPORT == _ON) && (_HW_DP_VSC_SDP_REG_SUPPORT != _ON))
    _SCALER_TIMER_EVENT_DP_RX1_MST2SST_RSV1_PACKET_DETECT,
#endif
#if(_DP_HDCP_2_2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_HDCP2_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP2_REPEATER_PROC_TIMEOUT,
#endif
#endif // End of #if(_DP_TX_SUPPORT == _ON)
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#endif // End of #if(_D1_DP_EXIST == _ON)

#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_MSG_TIMEOUT_EVENT,
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#if(_DP_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_CABLE_STATUS_CHANGE_EVENT,
    _SCALER_TIMER_EVENT_DP_TX_FORCE_REBUILD_TOPOLOGY_EVENT,
    _SCALER_TIMER_EVENT_DP_RX_MSG_COUNT_RESET_EVENT,
    _SCALER_TIMER_EVENT_DP_TX_MSG_COUNT_RESET_EVENT,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_WAITING_TO_READ_R0,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_WAITING_FOR_V_READY,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_POLLING_V_READY,
#if(_DP_TX_HPD_HIGH_DEBOUNCE_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_HPD_DEBOUNCE,
#endif
#if(_DP_HDCP_2_2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_READ_CERTIFICATE,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_READ_H_PRIME,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_READ_PAIRING_INFO,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_ENCRYPT_DATA,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_FOR_V_READY,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_POLLING_V_READY,
    _SCALER_TIMER_EVENT_DP_TX_HDCP2_WAITING_TO_READ_M_PRIME,
#endif
#endif // End of #if(_DP_TX_SUPPORT == _ON)
#if(_HDMI_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_HDMI_TX_CABLE_STATUS_CHANGE_EVENT,
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP_WAITING_TO_READ_R0,
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP_WAITING_FOR_V_READY,
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP_POLLING_V_READY,
#if(_HDMI_TX_HDCP_2_2_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP2_WAITING_TO_READ_CERTIFICATE,
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP2_WAITING_TO_READ_H_PRIME,
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP2_WAITING_TO_ENCRYPT_DATA,
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP2_WAITING_FOR_V_READY,
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP2_POLLING_V_READY,
    _SCALER_TIMER_EVENT_HDMI_TX_HDCP2_WAITING_TO_READ_M_PRIME,
#endif
#endif
#endif // End of #if(_DP_SUPPORT == _ON)

#if(_SDRAM_PHASE_CALIBRATION == _ON)
    _SCALER_TIMER_EVENT_SDRAM_PHASE_CNT_CHECK,
#endif

#if(_DDR1_PHASE_CALIBRATION == _ON)
    _SCALER_TIMER_EVENT_DDR_PHASE_CNT_CHECK,
#endif

#if(_D0_INPUT_PORT_TYPE == _D0_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX0_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX0_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX0_SWITCH_PORT_DISCOVERY_DONE,
#endif // End of #if(_D0_INPUT_PORT_TYPE == _D0_MHL_PORT)
#if(_D1_INPUT_PORT_TYPE == _D1_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX1_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX1_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX1_SWITCH_PORT_DISCOVERY_DONE,
#endif // End of #if(_D1_INPUT_PORT_TYPE == _D1_MHL_PORT)
#if(_D2_INPUT_PORT_TYPE == _D2_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX2_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX2_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX2_SWITCH_PORT_DISCOVERY_DONE,
#endif // End of #if(_D2_INPUT_PORT_TYPE == _D2_MHL_PORT)
#if(_D3_INPUT_PORT_TYPE == _D3_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX3_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX3_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX3_SWITCH_PORT_DISCOVERY_DONE,
#endif // End of #if(_D3_INPUT_PORT_TYPE == _D3_MHL_PORT)
#if(_D4_INPUT_PORT_TYPE == _D4_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX4_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX4_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX4_SWITCH_PORT_DISCOVERY_DONE,
#endif // End of #if(_D4_INPUT_PORT_TYPE == _D4_MHL_PORT)
#if(_D5_INPUT_PORT_TYPE == _D5_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX5_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX5_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX5_SWITCH_PORT_DISCOVERY_DONE,
#endif // End of #if(_D5_INPUT_PORT_TYPE == _D5_MHL_PORT)

#if((_DP_TYPE_C_PORT_CTRL_SUPPORT == _ON) && (_PORT_CONTROLLER_EMBEDDED_SUPPORT == _ON))
#if(_D0_DP_TYPE_C_PORT_CTRL_TYPE == _PORT_CONTROLLER_EMBEDDED)
    _SCALER_TIMER_EVENT_CC_RX0_STATE_TO_UNATTACH,
    _SCALER_TIMER_EVENT_CC_RX0_CLEAR_AC_ON_DEVICE_DETECT,
    _SCALER_TIMER_EVENT_PD_RX0_CBL_RESP_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_RX0_VDM_RESP_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_RX0_STATE_TO_READY,
    _SCALER_TIMER_EVENT_PD_RX0_SRC_TURN_ON_POWER,
    _SCALER_TIMER_EVENT_PD_RX0_SRC_TURN_OFF_POWER,
    _SCALER_TIMER_EVENT_PD_RX0_SEND_HARD_RST,
    _SCALER_TIMER_EVENT_PD_RX0_TPC_ERR_RECOVER,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_SRC_CAP_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_REQ_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_PARTNER_ALT_SUPPORT,
    _SCALER_TIMER_EVENT_PD_RX0_T480_ERROR_RECOVERY,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_PRS_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_DRS_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_VCS_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_CBL_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_SET_SRC_INIT_AMS,
    _SCALER_TIMER_EVENT_PD_RX0_PPS_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_RX0_S8_HRST,
    _SCALER_TIMER_EVENT_PD_RX0_DFP_START_ALT_MODE,
    _SCALER_TIMER_EVENT_PD_RX0_LENOVO_RESP_TIMEOUT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_ATTENTION_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_GET_SNK_CAP_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_VDMMSG_WAIT,
    _SCALER_TIMER_EVENT_PD_RX0_CLR_VDM_BUSY_FLAG,
#if(_TYPE_C_VENDOR_ALT_MODE == _TYPE_C_DELL_ALT_MODE)
    _SCALER_TIMER_EVENT_PD_RX0_DELL_ATTEN_RETRY,
#endif

#if(_TYPE_C_PMIC_TYPE != _PMIC_NONE)
    _SCALER_TIMER_EVENT_PMIC_TRACKING,
    _SCALER_TIMER_EVENT_PMIC_SAFETY_PROTECT,
    _SCALER_TIMER_EVENT_PMIC_POLLING_OCP,
#endif // End of #if(_TYPE_C_PMIC_TYPE != _PMIC_NONE)

#endif // End of #if(_D0_DP_TYPE_C_PORT_CTRL_TYPE == _PORT_CONTROLLER_EMBEDDED)
#endif // End of #if((_DP_TYPE_C_PORT_CTRL_SUPPORT == _ON) && (_PORT_CONTROLLER_EMBEDDED_SUPPORT == _ON))

#if(_SMBUS_BLOCK_READ_WRITE_COMMAND_SUPPORT == _ON)
   _SCALER_TIMER_EVENT_SMBUS_BLOCK_READ_WRITE,
#endif // End of #if(_SMBUS_BLOCK_READ_WRITE_COMMAND_SUPPORT == _ON)

// Background Fw Update Busy Timer
#if(_FW_UPDATE_BACKGROUND_SUPPORT == _ON)
#if(_DP_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_DPTX_BUSY,
#endif
#if(_DP_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_DPRX_BUSY,
#endif
#if(_DP_TYPE_C_PORT_CTRL_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_TYPEC_BUSY,
#endif
#if(_DIGITAL_PORT_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_MCCS_BUSY,
#endif
    _SCALER_TIMER_EVENT_BACKGROUND_FW_UPDATE_HDCP_BUSY,
#endif // End of #if(_FW_UPDATE_BACKGROUND_SUPPORT == _ON)

